name: Node.js CI

on:
  push:
      branches: [ "main" ]

jobs:
  build:
    runs-on: unbuntu-lastest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build --if-present
      - uses: actions/upload-artifact@v3
            with:
                name: Build
                path: dist
